//HintName: IA.MapEndpoints.g.cs
// <auto-generated />
#nullable enable

#pragma warning disable CS1591

public static partial class ApisServiceCollectionExtensions
{
	public static global::Microsoft.AspNetCore.Routing.RouteGroupBuilder MapCustomEndpoints(
		this global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder app,
		[global::System.Diagnostics.CodeAnalysis.StringSyntax("Route")] string prefix = ""
	)
	{
		var group = global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapGroup(app, prefix);

		global::Dummy.GetUsersQuery.MapEndpoint(group);


		return group;
	}
}
