//HintName: IA.Dummy.GetUsersQuery.g.cs
// <auto-generated />
#nullable enable

#pragma warning disable CS1591

namespace Dummy
{

	/// <remarks><see cref="global::Dummy.GetUsersQuery.Query" /> registered using <c>[<see cref="global::Microsoft.AspNetCore.Mvc.FromBodyAttribute" />]</c></remarks>
	partial class GetUsersQuery
	{
		internal static void MapEndpoint(global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder app)
		{
			var endpoint = global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapPost(
				app,
				"/api/users",
				async (
					[global::Microsoft.AspNetCore.Mvc.FromBodyAttribute] global::Dummy.GetUsersQuery.Query parameters,
					[global::Microsoft.AspNetCore.Mvc.FromServices] global::Dummy.GetUsersQuery.Handler handler,
					global::System.Threading.CancellationToken token
				) =>
				{
					var ret = await handler.HandleAsync(parameters, token);
					return ret;
				}
			);

			_ = global::Microsoft.AspNetCore.Builder.AuthorizationEndpointConventionBuilderExtensions.RequireAuthorization(endpoint, "AdminPolicy");

			endpoint = global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapPost(
				app,
				"/v1/users",
				async (
					[global::Microsoft.AspNetCore.Mvc.FromBodyAttribute] global::Dummy.GetUsersQuery.Query parameters,
					[global::Microsoft.AspNetCore.Mvc.FromServices] global::Dummy.GetUsersQuery.Handler handler,
					global::System.Threading.CancellationToken token
				) =>
				{
					var ret = await handler.HandleAsync(parameters, token);
					return ret;
				}
			);

			_ = global::Microsoft.AspNetCore.Builder.AuthorizationEndpointConventionBuilderExtensions.RequireAuthorization(endpoint, "AdminPolicy");

		}

		public static global::System.Collections.Generic.IReadOnlyList<string> Routes { get; } =
		[
			"/api/users",
			"/v1/users",
		];
	}
}
