//HintName: IA.Dummy.GetUsersQuery.g.cs
// <auto-generated />
#nullable enable

#pragma warning disable CS1591

namespace Dummy
{

	/// <remarks><see cref="global::Dummy.GetUsersQuery.Query" /> registered using <c>[<see cref="global::Microsoft.AspNetCore.Mvc.FromBodyAttribute" />]</c></remarks>
	partial class GetUsersQuery
	{
		internal static void MapEndpoint(global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder app)
		{
			var endpoint = global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapPut(
				app,
				"/route1",
				async (
					[global::Microsoft.AspNetCore.Mvc.FromBodyAttribute] global::Dummy.GetUsersQuery.Query parameters,
					[global::Microsoft.AspNetCore.Mvc.FromServices] global::Dummy.GetUsersQuery.Handler handler,
					global::System.Threading.CancellationToken token
				) =>
				{
					var ret = await handler.HandleAsync(parameters, token);
					return ret;
				}
			);

			endpoint = global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapPut(
				app,
				"/route2",
				async (
					[global::Microsoft.AspNetCore.Mvc.FromBodyAttribute] global::Dummy.GetUsersQuery.Query parameters,
					[global::Microsoft.AspNetCore.Mvc.FromServices] global::Dummy.GetUsersQuery.Handler handler,
					global::System.Threading.CancellationToken token
				) =>
				{
					var ret = await handler.HandleAsync(parameters, token);
					return ret;
				}
			);

			endpoint = global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapPut(
				app,
				"/route3",
				async (
					[global::Microsoft.AspNetCore.Mvc.FromBodyAttribute] global::Dummy.GetUsersQuery.Query parameters,
					[global::Microsoft.AspNetCore.Mvc.FromServices] global::Dummy.GetUsersQuery.Handler handler,
					global::System.Threading.CancellationToken token
				) =>
				{
					var ret = await handler.HandleAsync(parameters, token);
					return ret;
				}
			);

			endpoint = global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapPut(
				app,
				"/route4",
				async (
					[global::Microsoft.AspNetCore.Mvc.FromBodyAttribute] global::Dummy.GetUsersQuery.Query parameters,
					[global::Microsoft.AspNetCore.Mvc.FromServices] global::Dummy.GetUsersQuery.Handler handler,
					global::System.Threading.CancellationToken token
				) =>
				{
					var ret = await handler.HandleAsync(parameters, token);
					return ret;
				}
			);

			endpoint = global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapPut(
				app,
				"/route5",
				async (
					[global::Microsoft.AspNetCore.Mvc.FromBodyAttribute] global::Dummy.GetUsersQuery.Query parameters,
					[global::Microsoft.AspNetCore.Mvc.FromServices] global::Dummy.GetUsersQuery.Handler handler,
					global::System.Threading.CancellationToken token
				) =>
				{
					var ret = await handler.HandleAsync(parameters, token);
					return ret;
				}
			);

			endpoint = global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapPut(
				app,
				"/route6",
				async (
					[global::Microsoft.AspNetCore.Mvc.FromBodyAttribute] global::Dummy.GetUsersQuery.Query parameters,
					[global::Microsoft.AspNetCore.Mvc.FromServices] global::Dummy.GetUsersQuery.Handler handler,
					global::System.Threading.CancellationToken token
				) =>
				{
					var ret = await handler.HandleAsync(parameters, token);
					return ret;
				}
			);

			endpoint = global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapPut(
				app,
				"/route7",
				async (
					[global::Microsoft.AspNetCore.Mvc.FromBodyAttribute] global::Dummy.GetUsersQuery.Query parameters,
					[global::Microsoft.AspNetCore.Mvc.FromServices] global::Dummy.GetUsersQuery.Handler handler,
					global::System.Threading.CancellationToken token
				) =>
				{
					var ret = await handler.HandleAsync(parameters, token);
					return ret;
				}
			);

			endpoint = global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapPut(
				app,
				"/route8",
				async (
					[global::Microsoft.AspNetCore.Mvc.FromBodyAttribute] global::Dummy.GetUsersQuery.Query parameters,
					[global::Microsoft.AspNetCore.Mvc.FromServices] global::Dummy.GetUsersQuery.Handler handler,
					global::System.Threading.CancellationToken token
				) =>
				{
					var ret = await handler.HandleAsync(parameters, token);
					return ret;
				}
			);

			endpoint = global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapPut(
				app,
				"/route9",
				async (
					[global::Microsoft.AspNetCore.Mvc.FromBodyAttribute] global::Dummy.GetUsersQuery.Query parameters,
					[global::Microsoft.AspNetCore.Mvc.FromServices] global::Dummy.GetUsersQuery.Handler handler,
					global::System.Threading.CancellationToken token
				) =>
				{
					var ret = await handler.HandleAsync(parameters, token);
					return ret;
				}
			);

			endpoint = global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapPut(
				app,
				"/route10",
				async (
					[global::Microsoft.AspNetCore.Mvc.FromBodyAttribute] global::Dummy.GetUsersQuery.Query parameters,
					[global::Microsoft.AspNetCore.Mvc.FromServices] global::Dummy.GetUsersQuery.Handler handler,
					global::System.Threading.CancellationToken token
				) =>
				{
					var ret = await handler.HandleAsync(parameters, token);
					return ret;
				}
			);

		}

		public static global::System.Collections.Generic.IReadOnlyList<string> Routes { get; } =
		[
			"/route1",
			"/route2",
			"/route3",
			"/route4",
			"/route5",
			"/route6",
			"/route7",
			"/route8",
			"/route9",
			"/route10",
		];
	}
}
