//HintName: IA.Dummy..Root.g.cs
// <auto-generated />
#nullable enable

#pragma warning disable CS1591

namespace Dummy;

partial class Root
{
	internal static void MapGroup(global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder app, global::System.ReadOnlySpan<string> tags)
	{
		var group = global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapGroup(app, "api/root");


		global::Dummy.Root.Mid.MapGroup(group, tags);

	}

partial class Mid
{
	internal static void MapGroup(global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder app, global::System.ReadOnlySpan<string> tags)
	{
		var group = global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapGroup(app, "mid");

		CustomizeGroup(group);


		global::Dummy.Root.Mid.Inner.MapGroup(group, tags);

	}

partial class Inner
{
	internal static void MapGroup(global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder app, global::System.ReadOnlySpan<string> tags)
	{
		var group = global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapGroup(app, "inner");


		global::Dummy.GetUsersQuery.MapEndpoint(group);

	}

	public const string GetUsersQuery = "api/root/mid/inner/test";
}
}
}

partial class Root
{
	// old-fashioned inner-loop; should be fine since neither tags list will ever be large
	private static bool Intersects(
		global::System.ReadOnlySpan<string> first,
		global::System.ReadOnlySpan<string> second
	)
	{
		foreach (var f in first)
		{
			foreach (var s in second)
			{
				if (string.Equals(f, s, global::System.StringComparison.Ordinal))
					return true;
			}
		}

		return false;
	}
}
