//HintName: IA.Dummy.GetUsersQuery1.g.cs
// <auto-generated />
#nullable enable

#pragma warning disable CS1591

namespace Dummy
{

	/// <remarks><see cref="global::Dummy.GetUsersQuery1.Query" /> registered using <c>[<see cref="global::Microsoft.AspNetCore.Http.AsParametersAttribute" />]</c></remarks>
	partial class GetUsersQuery1
	{
		internal static void MapEndpoint(global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder app)
		{
			var endpoint = global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapGet(
				app,
				"test",
				async (
					[global::Microsoft.AspNetCore.Http.AsParametersAttribute] global::Dummy.GetUsersQuery1.Query parameters,
					[global::Microsoft.AspNetCore.Mvc.FromServices] global::Dummy.GetUsersQuery1.Handler handler,
					global::System.Threading.CancellationToken token
				) =>
				{
					var ret = await handler.HandleAsync(parameters, token);
					return ret;
				}
			);

		}

		public static global::System.Collections.Generic.IReadOnlyList<string> Routes { get; } =
		[
			"test",
		];

		public static string Route { get; } = "test";
	}
}
