//HintName: IA.Dummy..Root.g.cs
// <auto-generated />
#nullable enable

#pragma warning disable CS1591

namespace Dummy;

partial class Root
{
	internal static void MapGroup(global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder app)
	{
		var group = global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapGroup(app, "api/root");



		global::Dummy.Root.Mid.MapGroup(group);
	}


partial class Mid
{
	internal static void MapGroup(global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder app)
	{
		var group = global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapGroup(app, "mid");

		CustomizeGroup(group);


		global::Dummy.Root.Mid.Inner.MapGroup(group);
	}


partial class Inner
{
	internal static void MapGroup(global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder app)
	{
		var group = global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapGroup(app, "inner");


		global::Dummy.GetUsersQuery.MapEndpoint(group);

	}

	public const string GetUsersQuery = "api/root/mid/inner/test";

}
}
}
