//HintName: IH.Dummy.GetUsersQuery2.g.cs
// <auto-generated />
#nullable enable

#pragma warning disable CS1591

namespace Dummy;

partial class GetUsersQuery2
{
	public sealed partial class Handler : global::Immediate.Handlers.Shared.IHandler<global::Dummy.GetUsersQuery2.Query, int>
	{
		private readonly global::Dummy.GetUsersQuery2.HandleBehavior _handleBehavior;

		public Handler(
			global::Dummy.GetUsersQuery2.HandleBehavior handleBehavior
		)
		{
			var handlerType = typeof(GetUsersQuery2);

			_handleBehavior = handleBehavior;

		}

		public async global::System.Threading.Tasks.ValueTask<int> HandleAsync(
			global::Dummy.GetUsersQuery2.Query request,
			global::System.Threading.CancellationToken cancellationToken = default
		)
		{
			return await _handleBehavior
				.HandleAsync(request, cancellationToken)
				.ConfigureAwait(false);
		}
	}

	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
	public sealed class HandleBehavior : global::Immediate.Handlers.Shared.Behavior<global::Dummy.GetUsersQuery2.Query, int>
	{

		public HandleBehavior(
		)
		{
		}

		public override async global::System.Threading.Tasks.ValueTask<int> HandleAsync(
			global::Dummy.GetUsersQuery2.Query request,
			global::System.Threading.CancellationToken cancellationToken
		)
		{
			return await global::Dummy.GetUsersQuery2
				.Handle(
					request
					, cancellationToken
				)
				.ConfigureAwait(false);
		}
	}

	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
	public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddHandlers(
		global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
		global::Microsoft.Extensions.DependencyInjection.ServiceLifetime lifetime = global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Scoped
	)
	{
		services.Add(new(typeof(global::Dummy.GetUsersQuery2.Handler), typeof(global::Dummy.GetUsersQuery2.Handler), lifetime));
		services.Add(new(typeof(global::Immediate.Handlers.Shared.IHandler<global::Dummy.GetUsersQuery2.Query, int>), typeof(global::Dummy.GetUsersQuery2.Handler), lifetime));
		services.Add(new(typeof(global::Dummy.GetUsersQuery2.HandleBehavior), typeof(global::Dummy.GetUsersQuery2.HandleBehavior), lifetime));
		return services;
	}
}
