//HintName: IA.MapEndpoints.g.cs
// <auto-generated />
#nullable enable

#pragma warning disable CS1591

public static partial class ApisServiceCollectionExtensions
{
	public static global::Microsoft.AspNetCore.Routing.RouteGroupBuilder MapTestsEndpoints(
		this global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder app,
		[global::System.Diagnostics.CodeAnalysis.StringSyntax("Route")] string prefix = "",
		params string[] tags
	)
	{
		var group = global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapGroup(app, prefix);

		if (tags is [] || Intersects(tags, ["test"]))
		{

		global::Dummy.GetUsersQuery.MapEndpoint(group);
		}

		return group;
	}

	// old-fashioned inner-loop; should be fine since neither tags list will ever be large
	private static bool Intersects(
		global::System.ReadOnlySpan<string> first,
		global::System.ReadOnlySpan<string> second
	)
	{
		foreach (var f in first)
		{
			foreach (var s in second)
			{
				if (string.Equals(f, s, global::System.StringComparison.Ordinal))
					return true;
			}
		}

		return false;
	}
}
