<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<OutputType>Exe</OutputType>
  </PropertyGroup>

  <PropertyGroup Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net11.0'))">
	<Features>runtime-async=on</Features>
  </PropertyGroup>

  <ItemGroup Label="Usings">
	<Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="Immediate.Handlers" GeneratePathProperty="true" />
	<PackageReference Include="Microsoft.AspNetCore.Authorization" />
	<PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
	<PackageReference Include="Microsoft.CodeAnalysis.CSharp.Analyzer.Testing" />
	<PackageReference Include="Microsoft.CodeAnalysis.CSharp.CodeFix.Testing" />
	<PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" />
	<PackageReference Include="Microsoft.Extensions.DependencyInjection" />
	<PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
	<PackageReference Include="Scriban" />
	<PackageReference Include="Verify.SourceGenerators" />
	<PackageReference Include="Verify.XunitV3" />
	<PackageReference Include="xunit.v3.mtp-v2" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net11.0' ">
	<PackageReference Include="Basic.Reference.Assemblies.AspNet110" />
	<PackageReference Include="Basic.Reference.Assemblies.Net110" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net10.0' ">
	<PackageReference Include="Basic.Reference.Assemblies.AspNet100" />
	<PackageReference Include="Basic.Reference.Assemblies.Net100" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net9.0' ">
	<PackageReference Include="Basic.Reference.Assemblies.AspNet90" />
	<PackageReference Include="Basic.Reference.Assemblies.Net90" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net8.0' ">
	<PackageReference Include="Basic.Reference.Assemblies.AspNet80" />
	<PackageReference Include="Basic.Reference.Assemblies.Net80" />
  </ItemGroup>

  <ItemGroup>
	<ProjectReference Include="../../src/Immediate.Apis.Shared/Immediate.Apis.Shared.csproj" />
  </ItemGroup>

  <PropertyGroup>
	<RoslynVersion Condition=" '$(TargetFramework)' == 'net8.0' ">roslyn4.8</RoslynVersion>
	<RoslynVersion Condition=" '$(TargetFramework)' == 'net10.0' ">roslyn5.0</RoslynVersion>
	<RoslynVersion Condition=" '$(TargetFramework)' == 'net11.0' ">roslyn5.9</RoslynVersion>
  </PropertyGroup>

  <ItemGroup>
	<ProjectReference Include="../../src/Immediate.Apis.Analyzers/Immediate.Apis.Analyzers.csproj" ReferenceOutputAssembly="false">
	  <SetTargetFramework>TargetFramework=$(RoslynVersion)</SetTargetFramework>
	</ProjectReference>
	<Reference Include="../../src/Immediate.Apis.Analyzers/bin/$(Configuration)/$(RoslynVersion)/Immediate.Apis.Analyzers.dll" />

	<ProjectReference Include="../../src/Immediate.Apis.CodeFixes/Immediate.Apis.CodeFixes.csproj" ReferenceOutputAssembly="false">
	  <SetTargetFramework>TargetFramework=$(RoslynVersion)</SetTargetFramework>
	</ProjectReference>
	<Reference Include="../../src/Immediate.Apis.CodeFixes/bin/$(Configuration)/$(RoslynVersion)/Immediate.Apis.CodeFixes.dll" />

	<ProjectReference Include="../../src/Immediate.Apis.Generators/Immediate.Apis.Generators.csproj" ReferenceOutputAssembly="false">
	  <SetTargetFramework>TargetFramework=$(RoslynVersion)</SetTargetFramework>
	</ProjectReference>
	<Reference Include="../../src/Immediate.Apis.Generators/bin/$(Configuration)/$(RoslynVersion)/Immediate.Apis.Generators.dll" />

	<Reference Include="$(PkgImmediate_Handlers)/analyzers/dotnet/$(RoslynVersion)/cs/Immediate.Handlers.Generators.dll" />
  </ItemGroup>

</Project>
